name: SlugCraft CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Match your local version

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: |
          go build -v .
          go build -v ./cmd/slugcraft

      - name: Run Tests
        run: go test -v .

      - name: Run Benchmarks
        run: go test -bench=. -benchtime=1s .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Debug: Print Go environment
      - name: Debug Go Environment
        run: |
          go version
          go env

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.1  # Downgrade to test
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Lint
        run: golangci-lint run ./... --verbose  # Add verbose for more output